# Generated by Django 4.1.5 on 2023-05-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("imagen", models.CharField(max_length=200)),
            ],
        ),
    ]
