# Generated by Django 4.1.5 on 2023-06-02 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_producto_oferta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 2, 15, 14, 57, 248736)
                    ),
                ),
                ("total", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detalle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("precio", models.IntegerField()),
                ("cantidad", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.venta"
                    ),
                ),
            ],
        ),
    ]
